spring:
  application:
    name: user-app

chatbook:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8084,localhost:8085
    ServerListRefreshInterval: 2000

server:
  port: 9090

